name: gpu.cpp

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan1 mesa-vulkan-drivers ninja-build
      - run: python3 -m pip install numpy
      - run: tools/build_dawn.sh
      - run: ./test

  browser-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: emscripten-core/emsdk
          path: emsdk
          fetch-depth: 1
      - run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
      - run: ./test --build-web
        env:
          GPUCPP_EMSDK_ROOT: ${{ github.workspace }}/emsdk
