name: nix-linux

on: [push, pull_request]

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: |
          nix develop -c make tests
